[theme]
font = "sans serif"
primaryColor = "#004AAE"            # Berkeley Blue Medium

[theme.dark]
backgroundColor = "#0E1117"         # Dark main background
secondaryBackgroundColor = "#010133" # Berkeley Blue Dark for sidebar/widget background
textColor = "#FAFAFA"               # Light text

[theme.light]
backgroundColor = "#FFFFFF"         # Light main background
secondaryBackgroundColor = "#FFE88D" # Berkeley Gold Light for sidebar/widget background
textColor = "#31333F"               # Dark text